"""Study 5 -- Stage 18 placebo-table builder.

Reads ONLY results/stage18_placebo/informal_borrow_estimates.csv (itself
generated by code/study_05_crosscountry/stage18_placebo.py from raw Findex
microdata) and emits tab_stage8_placebo.tex. No coefficient, SE, p-value or
N is typed into the .tex file by hand.

Independent of, and does not modify, build_stage8_tables.py (primary tables)
or build_stage8_robustness_table.py (Stage 17 table).

Usage: python code/study_05_crosscountry/tables/build_stage8_placebo_table.py
"""
from __future__ import annotations

import csv
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[3]
SRC = PROJECT / "results/stage18_placebo/informal_borrow_estimates.csv"
OUT_TAB = PROJECT / "papers/study_05/manuscript/tables"


def read_rows() -> list[dict]:
    with SRC.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def stars(p_str: str) -> str:
    p = float(p_str)
    if p < 0.01:
        return "***"
    if p < 0.05:
        return "**"
    if p < 0.10:
        return "*"
    return ""


def fmt_pp(estimate_str: str) -> str:
    return f"{float(estimate_str) * 100.0:+.2f}"


def fmt_se(se_str: str) -> str:
    return f"({float(se_str) * 100.0:.2f})"


def fmt_p(p_str: str) -> str:
    return f"{float(p_str):.3f}"


def texttt_path(path: str) -> str:
    escaped = path.replace("_", "\\_").replace("/", "/\\allowbreak{}")
    return "\\texttt{" + escaped + "}"


def build(rows: list[dict]) -> str:
    idx = {(r["wave"], r["term"]): r for r in rows}
    dp21 = idx[("2021", "digital_payment")]
    dp24 = idx[("2024", "digital_payment")]
    ix21 = idx[("2021", "dig_x_lowcov")]
    ix24 = idx[("2024", "dig_x_lowcov")]

    dp21_s = fmt_pp(dp21["estimate"]) + stars(dp21["p_cluster"])
    dp24_s = fmt_pp(dp24["estimate"]) + stars(dp24["p_cluster"])
    ix21_s = fmt_pp(ix21["estimate"]) + stars(ix21["p_cluster"])
    ix24_s = fmt_pp(ix24["estimate"]) + stars(ix24["p_cluster"])

    return f"""\\begin{{table}}[htbp]
\\centering
\\caption{{Placebo check: informal borrowing, 2021 and 2024}}
\\label{{tab:stage8placebo}}
\\begin{{adjustbox}}{{max width=\\textwidth}}
\\begin{{tabular}}{{lrr}}
\\toprule
 & 2021 & 2024 \\\\
\\midrule
Digital payment association (pp) & {dp21_s} & {dp24_s} \\\\
Payment $\\times$ lower 2019 coverage (pp) & {ix21_s} & {ix24_s} \\\\
Clustered SE, interaction (pp) & {fmt_se(ix21['se_cluster'])} & {fmt_se(ix24['se_cluster'])} \\\\
Wild-cluster $p$, interaction & {fmt_p(ix21['wild_p_rademacher'])} & {fmt_p(ix24['wild_p_rademacher'])} \\\\
Observations & {int(float(ix21['N'])):,} & {int(float(ix24['N'])):,} \\\\
Economies & {int(float(ix21['G']))} & {int(float(ix24['G']))} \\\\
\\bottomrule
\\end{{tabular}}
\\end{{adjustbox}}
\\smallskip
\\begin{{minipage}}{{\\linewidth}}\\footnotesize \\emph{{Notes.}}
Outcome is \\texttt{{informal\\_borrow}} (borrowed from family or friends in the past 12
months), constructed from \\texttt{{fin22b}} exactly as in the frozen H-000500 record.
Same M2 specification, weighting and null-imposed cluster-score Rademacher wild-cluster
inference (999 replications) as the primary formal-borrowing model. *** denotes clustered
$p<0.01$, ** $p<0.05$, * $p<0.10$. Generated by
{texttt_path('code/study_05_crosscountry/tables/build_stage8_placebo_table.py')} from
{texttt_path('results/stage18_placebo/informal_borrow_estimates.csv')}.\\end{{minipage}}
\\end{{table}}
"""


def main() -> None:
    rows = read_rows()
    OUT_TAB.mkdir(parents=True, exist_ok=True)
    (OUT_TAB / "tab_stage8_placebo.tex").write_text(build(rows), encoding="utf-8")
    print("Wrote tab_stage8_placebo.tex from results/stage18_placebo/informal_borrow_estimates.csv.")


if __name__ == "__main__":
    main()
