"""Reviewer-response audit: differential missingness, overall R2 and LPM bounds."""
from __future__ import annotations
import hashlib,json
from datetime import datetime,timezone
from pathlib import Path
import numpy as np,pandas as pd,patsy,statsmodels.api as sm
ROOT=Path(__file__).resolve().parents[4]; P=ROOT/"projects/study_05_findex_crosscountry"; OUT=P/"results/stage3/CODEX-S5-REVIEWER-CHECKS-20260914-001"; M2="anydigpayment + anydigpayment:lowcov2019_z + account_fin + account_fin:lowcov2019_z + female_d + age_c + age_c2 + C(educ) + C(inc_q) + urban_d + C(iso3)"
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 if OUT.exists(): raise RuntimeError("immutable output collision")
 source=ROOT/"data/raw/data_micro_findex_2024_vietnam.xlsx"; snap=P/"data/raw/wb_credit_information_latest_snapshot.csv"; panel=P/"results/stage1/CODEX-S5-BUILD-20260909-001/analysis_panel.csv"
 cols=["wpid_random","economycode","regionwb","wgt","fin22a","anydigpayment","account_fin","female","age","educ","inc_q","urbanicity"]
 x=pd.read_excel(source,sheet_name="findex_microdata_2025_labelled_",usecols=cols); x=x[x.fin22a.isin([1,2])].copy(); s=pd.read_csv(snap); s["any_cov"]=s[["credit_bureau_cov_pct","credit_registry_cov_pct"]].max(axis=1,skipna=True); x=x.merge(s[["iso3","any_cov"]],left_on="economycode",right_on="iso3",how="left",validate="many_to_one"); x["coverage_group"]=pd.qcut(x.any_cov,4,labels=["Q1 lowest","Q2","Q3","Q4 highest"],duplicates="drop"); x["missing_any_control"]=x[["educ","inc_q","urbanicity"]].isna().any(axis=1)
 rows=[]
 for group,col in [("coverage_quartile","coverage_group"),("region","regionwb")]:
  for name,g in x.groupby(col,dropna=False,observed=True): rows.append({"stratum_type":group,"stratum":str(name),"N_outcome_valid":len(g),"missing_educ":int(g.educ.isna().sum()),"missing_inc_q":int(g.inc_q.isna().sum()),"missing_urbanicity":int(g.urbanicity.isna().sum()),"missing_any_control":int(g.missing_any_control.sum()),"missing_any_rate":float(g.missing_any_control.mean()),"mean_coverage":float(g.any_cov.mean())})
 d=pd.read_csv(panel); y,X=patsy.dmatrices("formal_borrow ~ "+M2,d,return_type="dataframe"); q=d.loc[X.index]; fit=sm.WLS(y.iloc[:,0],X,weights=q.w_equal).fit(); pred=np.asarray(fit.fittedvalues); overall=float(fit.rsquared); within=float(1-np.sum(q.w_equal*(y.iloc[:,0]-pred)**2)/np.sum(q.w_equal*(y.iloc[:,0]-q.groupby("iso3").formal_borrow.transform(lambda z:np.average(z,weights=q.loc[z.index,"w_equal"])))**2)); bounds={"below_zero":int((pred<0).sum()),"above_one":int((pred>1).sum()),"share_outside":float(((pred<0)|(pred>1)).mean()),"min":float(pred.min()),"max":float(pred.max())}
 OUT.mkdir(parents=True); pd.DataFrame(rows).to_csv(OUT/"missingness_by_coverage_region.csv",index=False)
 result={"run_id":"CODEX-S5-REVIEWER-CHECKS-20260914-001","status":"POST_RESULT_DIAGNOSTIC","sample":{"outcome_valid":len(x),"economies":int(x.economycode.nunique()),"missing_education":int(x.educ.isna().sum()),"missing_income_quintile":int(x.inc_q.isna().sum()),"missing_urbanicity":int(x.urbanicity.isna().sum()),"missing_any_of_three":int(x.missing_any_control.sum()),"complete":int((~x.missing_any_control).sum())},"M2_fit":{"overall_r2":overall,"within_r2_recomputed":within,"prediction_bounds":bounds,"N":len(q),"G":int(q.iso3.nunique())},"data_challenge":{"artifact_inventory":[str(source),str(snap),str(panel)],"variable_lineage":{"missingness":"Findex raw educ/inc_q/urbanicity after valid fin22a","coverage":"World Bank snapshot max(private bureau, public registry)","R2":"M2 WLS on frozen analysis panel"},"coverage":"98 outcome-valid economies before listwise controls; 97 final economies","quality_findings":["Missingness is descriptive and post-result; it cannot prove missing-at-random","Outcome-module availability remains the dominant sample-selection event"],"merge_audit":"many-to-one ISO3 merge to coverage snapshot","leakage_and_revision_risks":"No future variable is introduced; 2019 moderator vintage remains disclosed","unverified_semantics":[],"design_support":"Supports a differential-missingness diagnostic and transparent fit reporting, not correction for non-random missingness","feasibility_verdict":"FEASIBLE_WITH_LIMITATIONS"},"input_sha256":{"micro":sha(source),"snapshot":sha(snap),"panel":sha(panel)},"created_utc":datetime.now(timezone.utc).isoformat()}; (OUT/"result.json").write_text(json.dumps(result,indent=2),encoding="utf-8"); print(json.dumps(result,indent=2))
if __name__=="__main__": main()
